// <auto-generated />
using System;
using DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(MaravilContext))]
    [Migration("20221007203952_AddingAmountToOrders")]
    partial class AddingAmountToOrders
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BAL.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CellPhone2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ModifiedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TownId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ModifiedByUserId");

                    b.HasIndex("TownId");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("BAL.Models.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDelivered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("BAL.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("State", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boaco"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carazo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chinandega"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chontales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Costa Caribe Norte"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Costa Caribe Sur"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Estelí"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Granada"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jinotega"
                        },
                        new
                        {
                            Id = 10,
                            Name = "León"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Madriz"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Managua"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Masaya"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Matagalpa"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Nueva Segovia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Río San Juan"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Rivas"
                        });
                });

            modelBuilder.Entity("BAL.Models.Town", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Town", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boaco",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Camoapa",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "San José de los Remates",
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "San Lorenzo",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Santa Lucía",
                            StateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Teustepe",
                            StateId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Diriamba",
                            StateId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dolores",
                            StateId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "El Rosario",
                            StateId = 2
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jinotepe",
                            StateId = 2
                        },
                        new
                        {
                            Id = 11,
                            Name = "La Conquista",
                            StateId = 2
                        },
                        new
                        {
                            Id = 12,
                            Name = "La Paz de Oriente",
                            StateId = 2
                        },
                        new
                        {
                            Id = 13,
                            Name = "San Marcos",
                            StateId = 2
                        },
                        new
                        {
                            Id = 14,
                            Name = "Santa Teresa",
                            StateId = 2
                        },
                        new
                        {
                            Id = 15,
                            Name = "Chichigalpa",
                            StateId = 3
                        },
                        new
                        {
                            Id = 16,
                            Name = "Chinandega",
                            StateId = 3
                        },
                        new
                        {
                            Id = 17,
                            Name = "Cinco Pinos",
                            StateId = 3
                        },
                        new
                        {
                            Id = 18,
                            Name = "Corinto",
                            StateId = 3
                        },
                        new
                        {
                            Id = 19,
                            Name = "El Realejo",
                            StateId = 3
                        },
                        new
                        {
                            Id = 20,
                            Name = "El Viejo",
                            StateId = 3
                        },
                        new
                        {
                            Id = 21,
                            Name = "Posoltega",
                            StateId = 3
                        },
                        new
                        {
                            Id = 22,
                            Name = "Puerto Morazán",
                            StateId = 3
                        },
                        new
                        {
                            Id = 23,
                            Name = "San Francisco del Norte",
                            StateId = 3
                        },
                        new
                        {
                            Id = 24,
                            Name = "San Pedro del Norte",
                            StateId = 3
                        },
                        new
                        {
                            Id = 25,
                            Name = "Santo Tomás del Norte",
                            StateId = 3
                        },
                        new
                        {
                            Id = 26,
                            Name = "Somotillo",
                            StateId = 3
                        },
                        new
                        {
                            Id = 27,
                            Name = "Villanueva",
                            StateId = 3
                        },
                        new
                        {
                            Id = 28,
                            Name = "Acoyapa",
                            StateId = 4
                        },
                        new
                        {
                            Id = 29,
                            Name = "Comalapa",
                            StateId = 4
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cuapa",
                            StateId = 4
                        },
                        new
                        {
                            Id = 31,
                            Name = "El Coral",
                            StateId = 4
                        },
                        new
                        {
                            Id = 32,
                            Name = "Juigalpa",
                            StateId = 4
                        },
                        new
                        {
                            Id = 33,
                            Name = "La Libertad",
                            StateId = 4
                        },
                        new
                        {
                            Id = 34,
                            Name = "San Pedro de Lóvago",
                            StateId = 4
                        },
                        new
                        {
                            Id = 35,
                            Name = "Santo Domingo",
                            StateId = 4
                        },
                        new
                        {
                            Id = 36,
                            Name = "Santo Tomás",
                            StateId = 4
                        },
                        new
                        {
                            Id = 37,
                            Name = "Villa Sandino",
                            StateId = 4
                        },
                        new
                        {
                            Id = 38,
                            Name = "Bonanza",
                            StateId = 5
                        },
                        new
                        {
                            Id = 39,
                            Name = "Mulukukú",
                            StateId = 5
                        },
                        new
                        {
                            Id = 40,
                            Name = "Prinzapolka",
                            StateId = 5
                        },
                        new
                        {
                            Id = 41,
                            Name = "Puerto Cabezas",
                            StateId = 5
                        },
                        new
                        {
                            Id = 42,
                            Name = "Rosita",
                            StateId = 5
                        },
                        new
                        {
                            Id = 43,
                            Name = "Siuna",
                            StateId = 5
                        },
                        new
                        {
                            Id = 44,
                            Name = "Waslala",
                            StateId = 5
                        },
                        new
                        {
                            Id = 45,
                            Name = "Waspán",
                            StateId = 5
                        },
                        new
                        {
                            Id = 46,
                            Name = "Bluefields",
                            StateId = 6
                        },
                        new
                        {
                            Id = 47,
                            Name = "Corn Island",
                            StateId = 6
                        },
                        new
                        {
                            Id = 48,
                            Name = "Desembocadura de Río Grande",
                            StateId = 6
                        },
                        new
                        {
                            Id = 49,
                            Name = "El Ayote",
                            StateId = 6
                        },
                        new
                        {
                            Id = 50,
                            Name = "El Rama",
                            StateId = 6
                        },
                        new
                        {
                            Id = 51,
                            Name = "El Tortuguero",
                            StateId = 6
                        },
                        new
                        {
                            Id = 52,
                            Name = "Kukra Hill",
                            StateId = 6
                        },
                        new
                        {
                            Id = 53,
                            Name = "La Cruz de Río Grande",
                            StateId = 6
                        },
                        new
                        {
                            Id = 54,
                            Name = "Laguna de Perlas",
                            StateId = 6
                        },
                        new
                        {
                            Id = 55,
                            Name = "Muelle de los Bueyes",
                            StateId = 6
                        },
                        new
                        {
                            Id = 56,
                            Name = "Nueva Guinea",
                            StateId = 6
                        },
                        new
                        {
                            Id = 57,
                            Name = "Paiwas",
                            StateId = 6
                        },
                        new
                        {
                            Id = 58,
                            Name = "Condega",
                            StateId = 7
                        },
                        new
                        {
                            Id = 59,
                            Name = "Estelí",
                            StateId = 7
                        },
                        new
                        {
                            Id = 60,
                            Name = "La Trinidad",
                            StateId = 7
                        },
                        new
                        {
                            Id = 61,
                            Name = "Pueblo Nuevo",
                            StateId = 7
                        },
                        new
                        {
                            Id = 62,
                            Name = "San Juan de Limay",
                            StateId = 7
                        },
                        new
                        {
                            Id = 63,
                            Name = "San Nicolás",
                            StateId = 7
                        },
                        new
                        {
                            Id = 64,
                            Name = "Diriá",
                            StateId = 8
                        },
                        new
                        {
                            Id = 65,
                            Name = "Diriomo",
                            StateId = 8
                        },
                        new
                        {
                            Id = 66,
                            Name = "Granada",
                            StateId = 8
                        },
                        new
                        {
                            Id = 67,
                            Name = "Nandaime",
                            StateId = 8
                        },
                        new
                        {
                            Id = 68,
                            Name = "El Cuá",
                            StateId = 9
                        },
                        new
                        {
                            Id = 69,
                            Name = "Jinotega",
                            StateId = 9
                        },
                        new
                        {
                            Id = 70,
                            Name = "La Concordia",
                            StateId = 9
                        },
                        new
                        {
                            Id = 71,
                            Name = "San José de Bocay",
                            StateId = 9
                        },
                        new
                        {
                            Id = 72,
                            Name = "San Rafael del Norte",
                            StateId = 9
                        },
                        new
                        {
                            Id = 73,
                            Name = "San Sebastián de Yalí",
                            StateId = 9
                        },
                        new
                        {
                            Id = 74,
                            Name = "Santa María de Pantasma",
                            StateId = 9
                        },
                        new
                        {
                            Id = 75,
                            Name = "Wiwilí de Jinotega",
                            StateId = 9
                        },
                        new
                        {
                            Id = 76,
                            Name = "Achuapa",
                            StateId = 10
                        },
                        new
                        {
                            Id = 77,
                            Name = "El Jicaral",
                            StateId = 10
                        },
                        new
                        {
                            Id = 78,
                            Name = "El Sauce",
                            StateId = 10
                        },
                        new
                        {
                            Id = 79,
                            Name = "La Paz Centro",
                            StateId = 10
                        },
                        new
                        {
                            Id = 80,
                            Name = "Larreynaga",
                            StateId = 10
                        },
                        new
                        {
                            Id = 81,
                            Name = "León",
                            StateId = 10
                        },
                        new
                        {
                            Id = 82,
                            Name = "Nagarote",
                            StateId = 10
                        },
                        new
                        {
                            Id = 83,
                            Name = "Quezalguaque",
                            StateId = 10
                        },
                        new
                        {
                            Id = 84,
                            Name = "Santa Rosa del Peñón",
                            StateId = 10
                        },
                        new
                        {
                            Id = 85,
                            Name = "Telica",
                            StateId = 10
                        },
                        new
                        {
                            Id = 86,
                            Name = "Las Sabanas",
                            StateId = 11
                        },
                        new
                        {
                            Id = 87,
                            Name = "Palacagüina",
                            StateId = 11
                        },
                        new
                        {
                            Id = 88,
                            Name = "San José de Cusmapa",
                            StateId = 11
                        },
                        new
                        {
                            Id = 89,
                            Name = "San Juan de Río Coco",
                            StateId = 11
                        },
                        new
                        {
                            Id = 90,
                            Name = "San Lucas",
                            StateId = 11
                        },
                        new
                        {
                            Id = 91,
                            Name = "Somoto",
                            StateId = 11
                        },
                        new
                        {
                            Id = 92,
                            Name = "Telpaneca",
                            StateId = 11
                        },
                        new
                        {
                            Id = 93,
                            Name = "Totogalpa",
                            StateId = 11
                        },
                        new
                        {
                            Id = 94,
                            Name = "Yalagüina",
                            StateId = 11
                        },
                        new
                        {
                            Id = 95,
                            Name = "Ciudad Sandino",
                            StateId = 12
                        },
                        new
                        {
                            Id = 96,
                            Name = "El Crucero",
                            StateId = 12
                        },
                        new
                        {
                            Id = 97,
                            Name = "Managua",
                            StateId = 12
                        },
                        new
                        {
                            Id = 98,
                            Name = "Mateare",
                            StateId = 12
                        },
                        new
                        {
                            Id = 99,
                            Name = "San Francisco Libre",
                            StateId = 12
                        },
                        new
                        {
                            Id = 100,
                            Name = "San Rafael del Sur",
                            StateId = 12
                        },
                        new
                        {
                            Id = 101,
                            Name = "Ticuantepe",
                            StateId = 12
                        },
                        new
                        {
                            Id = 102,
                            Name = "Tipitapa",
                            StateId = 12
                        },
                        new
                        {
                            Id = 103,
                            Name = "Villa El Carmen",
                            StateId = 12
                        },
                        new
                        {
                            Id = 104,
                            Name = "Catarina",
                            StateId = 13
                        },
                        new
                        {
                            Id = 105,
                            Name = "La Concepción",
                            StateId = 13
                        },
                        new
                        {
                            Id = 106,
                            Name = "Masatepe",
                            StateId = 13
                        },
                        new
                        {
                            Id = 107,
                            Name = "Masaya",
                            StateId = 13
                        },
                        new
                        {
                            Id = 108,
                            Name = "Nandasmo",
                            StateId = 13
                        },
                        new
                        {
                            Id = 109,
                            Name = "Nindirí",
                            StateId = 13
                        },
                        new
                        {
                            Id = 110,
                            Name = "Niquinohomo",
                            StateId = 13
                        },
                        new
                        {
                            Id = 111,
                            Name = "San Juan de Oriente",
                            StateId = 13
                        },
                        new
                        {
                            Id = 112,
                            Name = "Tisma",
                            StateId = 13
                        },
                        new
                        {
                            Id = 113,
                            Name = "Ciudad Darío",
                            StateId = 14
                        },
                        new
                        {
                            Id = 114,
                            Name = "El Tuma - La Dalia",
                            StateId = 14
                        },
                        new
                        {
                            Id = 115,
                            Name = "Esquipulas",
                            StateId = 14
                        },
                        new
                        {
                            Id = 116,
                            Name = "Matagalpa",
                            StateId = 14
                        },
                        new
                        {
                            Id = 117,
                            Name = "Matiguás",
                            StateId = 14
                        },
                        new
                        {
                            Id = 118,
                            Name = "Muy Muy",
                            StateId = 14
                        },
                        new
                        {
                            Id = 119,
                            Name = "Rancho Grande",
                            StateId = 14
                        },
                        new
                        {
                            Id = 120,
                            Name = "Río Blanco",
                            StateId = 14
                        },
                        new
                        {
                            Id = 121,
                            Name = "San Dionisio",
                            StateId = 14
                        },
                        new
                        {
                            Id = 122,
                            Name = "San Isidro",
                            StateId = 14
                        },
                        new
                        {
                            Id = 123,
                            Name = "San Ramón",
                            StateId = 14
                        },
                        new
                        {
                            Id = 124,
                            Name = "Sébaco",
                            StateId = 14
                        },
                        new
                        {
                            Id = 125,
                            Name = "Terrabona",
                            StateId = 14
                        },
                        new
                        {
                            Id = 126,
                            Name = "Ciudad Antigua",
                            StateId = 15
                        },
                        new
                        {
                            Id = 127,
                            Name = "Dipilto",
                            StateId = 15
                        },
                        new
                        {
                            Id = 128,
                            Name = "El Jícaro",
                            StateId = 15
                        },
                        new
                        {
                            Id = 129,
                            Name = "Jalapa",
                            StateId = 15
                        },
                        new
                        {
                            Id = 130,
                            Name = "Macuelizo",
                            StateId = 15
                        },
                        new
                        {
                            Id = 131,
                            Name = "Mozonte",
                            StateId = 15
                        },
                        new
                        {
                            Id = 132,
                            Name = "Murra",
                            StateId = 15
                        },
                        new
                        {
                            Id = 133,
                            Name = "Ocotal",
                            StateId = 15
                        },
                        new
                        {
                            Id = 134,
                            Name = "Quilalí",
                            StateId = 15
                        },
                        new
                        {
                            Id = 135,
                            Name = "San Fernando",
                            StateId = 15
                        },
                        new
                        {
                            Id = 136,
                            Name = "Santa María",
                            StateId = 15
                        },
                        new
                        {
                            Id = 137,
                            Name = "Wiwilí",
                            StateId = 15
                        },
                        new
                        {
                            Id = 138,
                            Name = "El Almendro",
                            StateId = 16
                        },
                        new
                        {
                            Id = 139,
                            Name = "El Castillo",
                            StateId = 16
                        },
                        new
                        {
                            Id = 140,
                            Name = "Morrito",
                            StateId = 16
                        },
                        new
                        {
                            Id = 141,
                            Name = "San Carlos",
                            StateId = 16
                        },
                        new
                        {
                            Id = 142,
                            Name = "San Juan del Norte",
                            StateId = 16
                        },
                        new
                        {
                            Id = 143,
                            Name = "San Miguelito",
                            StateId = 16
                        },
                        new
                        {
                            Id = 144,
                            Name = "Altagracia",
                            StateId = 17
                        },
                        new
                        {
                            Id = 145,
                            Name = "Belén",
                            StateId = 17
                        },
                        new
                        {
                            Id = 146,
                            Name = "Buenos Aires",
                            StateId = 17
                        },
                        new
                        {
                            Id = 147,
                            Name = "Cárdenas",
                            StateId = 17
                        },
                        new
                        {
                            Id = 148,
                            Name = "Moyogalpa",
                            StateId = 17
                        },
                        new
                        {
                            Id = 149,
                            Name = "Potosí",
                            StateId = 17
                        },
                        new
                        {
                            Id = 150,
                            Name = "Rivas",
                            StateId = 17
                        },
                        new
                        {
                            Id = 151,
                            Name = "San Jorge",
                            StateId = 17
                        },
                        new
                        {
                            Id = 152,
                            Name = "San Juan del Sur",
                            StateId = 17
                        },
                        new
                        {
                            Id = 153,
                            Name = "Tola",
                            StateId = 17
                        });
                });

            modelBuilder.Entity("BAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("ActiveStatus")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveStatus = true,
                            CreatedOn = new DateTime(2022, 10, 7, 14, 39, 52, 626, DateTimeKind.Local).AddTicks(632),
                            IsSystemAdmin = true,
                            ModifiedOn = new DateTime(2022, 10, 7, 14, 39, 52, 626, DateTimeKind.Local).AddTicks(641),
                            Password = "bca6062db9ffe0bdb13f01b5dc48f6e0e7d0f8c8a21af0324c9971d3fbd51e08",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("BAL.Models.Client", b =>
                {
                    b.HasOne("BAL.Models.User", "CreatedByUser")
                        .WithMany("ClientsCreators")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAL.Models.User", "ModifiedByUser")
                        .WithMany("ClientsModificators")
                        .HasForeignKey("ModifiedByUserId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("BAL.Models.Town", "Town")
                        .WithMany("Clients")
                        .HasForeignKey("TownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("ModifiedByUser");

                    b.Navigation("Town");
                });

            modelBuilder.Entity("BAL.Models.Order", b =>
                {
                    b.HasOne("BAL.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("BAL.Models.Town", b =>
                {
                    b.HasOne("BAL.Models.State", "State")
                        .WithMany("Towns")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("BAL.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BAL.Models.State", b =>
                {
                    b.Navigation("Towns");
                });

            modelBuilder.Entity("BAL.Models.Town", b =>
                {
                    b.Navigation("Clients");
                });

            modelBuilder.Entity("BAL.Models.User", b =>
                {
                    b.Navigation("ClientsCreators");

                    b.Navigation("ClientsModificators");
                });
#pragma warning restore 612, 618
        }
    }
}
